<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $number
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findXLastVotes($number)
    {
        return $this->createQueryBuilder('e')->
        setMaxResults($number)->
        orderBy('e.id','DESC')->
        getQuery()->
        getResult();

    }

    public function findLast5VoteForUser(User $user)
    {
        return $this->createQueryBuilder('e')->where('e.user = :user')
            ->setParameter('user', $user)->
            orderBy('e.id','DESC')->
            setMaxResults(5)->
            getQuery()->
            getResult();

    }
}
